before:
  hooks:
    - go mod download
project_name: hioctl
builds:
- env:
  - CGO_ENABLED=0
  ldflags: -s -w -X github.com/hive-io/hive-go-client/cmd.version={{.Version}} -X github.com/hive-io/hive-go-client/cmd.date={{.CommitDate}} -X github.com/hive-io/hive-go-client/cmd.commit={{ .Commit }}
  main: ./hioctl/main.go
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
archives:
- format_overrides:
  - goos: windows
    format: zip
nfpms:
- package_name: hioctl
  homepage:  https://hiveio.com
  description: hiveio rest api client
  maintainer: John Mullen <john.mullen@hiveio.com>
  license: MPL
  vendor: HiveIO
  formats:
  - deb
  - rpm
  bindir: /usr/bin
  contents:
   - src: files/completion/bash/hioctl
     dst: /usr/share/bash-completion/completions/hioctl
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs'
    - '^chore'
